### ISSUE TITLE
A Widget/Picture In Picture Feature!

### ISSUE THREAD

**Issue by mackdroid** [Diego-Ivan/Flowtime#15]
https://user-images.githubusercontent.com/68280146/164981137-b49f109f-e777-4b2e-b809-19dce9d8dc3b.mp4

A feature like Window's 10's task manager, a tiny widget that takes tiny amount of space, maybe even a option to position itself over a window

for a person with adhd even fighting against a simple timer can make a person much more productive, a feature like this could help me greatly

**Comment by Diego-Ivan** [comment]
I like this idea. Maybe something like a *Distraction Free mode* that resembles older versions of Flowtime.

![](https://raw.githubusercontent.com/Diego-Ivan/Flowtime/1.0.0/data/screenshots/02.png)

**Comment by Diego-Ivan** [comment]
This is what I have done so far. It's still work-in-progress but looks fine. GTK cannot position their windows above others, but in order to work around this limitation I've made that in this mode, every place you secondary-click on will open the contextual window menu that your DE provides, so you can enable that preference there :smile:.

https://user-images.githubusercontent.com/76420970/165016789-a6cf9583-7f98-4746-87ce-2845b3d6d88b.mp4

https://user-images.githubusercontent.com/76420970/165017109-71411614-06ea-4e8e-bf12-cffc0a0ad095.mp4

**Comment by Diego-Ivan** [comment]
So, this feature has been finally merged! I will be testing it along with other important changes today and will probably arrive Flathub tomorrow!
