### ISSUE TITLE
Cannot take break after five minutes

### ISSUE THREAD

**Issue by cedewey** [Diego-Ivan/Flowtime#2]
If I set the "Time until break" to five minutes, then try taking a break after that time, the app does not respond and instead keeps me in the working mode.

https://www.loom.com/share/819f173671aa4cd494838f6fac6ab984

**Comment by Diego-Ivan** [comment]
Hey, thanks for reporting this 😄.
The 'Time until break' setting will only be applied when you start the next working session, so probably that's why it's not working for you.
Anyway, this feature has been removed in a WIP branch as it does not make too much sense in the Flowtime technique. I think I'll apply those changes to main too and push them to Flathub.

**Comment by Diego-Ivan** [comment]
I've pushed the changes to Flathub. An update will be available in a few hours 😄

**Comment by cedewey** [comment]
That was fast, thanks!
